/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    //application
    war
    id("mx.com.inftel.wildfly") version "1.0.2"
    //id("org.hibernate.orm") version "6.1.7.Final"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.postgresql:postgresql:42.5.4")
    implementation("org.hibernate.orm:hibernate-core:6.1.7.Final")
    implementation("org.hibernate.validator:hibernate-validator:8.0.1.Final")
    implementation("org.eclipse:yasson:3.0.3")
    implementation("org.glassfish.expressly:expressly:5.0.0")
    implementation("org.primefaces:primefaces:12.0.0:jakarta")

    implementation("jakarta.platform:jakarta.jakartaee-web-api:9.0.0")
    implementation("jakarta.faces:jakarta.faces-api:4.0.1")
}

/* 
application {
    // Define the main class for the application.
    mainClass.set("Main")
}
*/



tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

wildfly {

    // Optional. Default value: "remote+http://localhost:9990".
    controller = extra["wildfly.port"] as String

    // Optional. Default value: null (unset).
    //username = "AnastasiaPronina"
    username = extra["wildfly.user"] as String

    // Optional. Default value: null (unset).
    //password = "89111984456Hp"
    password = extra["wildfly.password"] as String

    // Required. Processed with "Project.file()" method.
    deployment = "build/libs/app.war"

    // Optional. Default value: true.
    persistent = false
}

tasks.build {
    dependsOn(tasks.wildflyDeploy)
}
